#!/bin/bash

berryc save_monitor 0 0
berryc save_monitor 1 1
berryc save_monitor 2 0
berryc save_monitor 3 1
berryc save_monitor 4 0
berryc save_monitor 5 1
berryc save_monitor 6 0
berryc save_monitor 7 1
berryc save_monitor 8 0
berryc save_monitor 9 1


# Set decoration geometry
berryc border_width       3
berryc inner_border_width 1
berryc title_height       0
berryc top_gap            30

. "${HOME}/.cache/wal/colors.sh"


# Set decoration colors
# berryc focus_color         292D3E
# berryc unfocus_color       292D3E
# berryc inner_focus_color   FFCB6B
# berryc inner_unfocus_color 565679
# berryc text_focus_color    ffffff
# berryc text_unfocus_color  eeeeee

berryc focus_color "${color3#\#}"
berryc unfocus_color "${color0#\#}"
berryc inner_focus_color "${color3#\#}"
berryc inner_unfocus_color "${color0#\#}"
berryc text_focus_color "${color15#\#}"
berryc text_focus_color "${color7#\#}"

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Dina-9"

# background
feh --bg-scale ~/.config/wallpapers/zhongli_hutao.jpg

# bar (doesn't work with bash??? pls fix)
zsh ~/.config/lemonbar/peepeenoborders

# security smh
xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
