#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

if [ $( xrandr | grep ' connected' | wc -l ) = 2 ]
then
    xrandr --output eDP1 --auto --output HDMI1 --scale 1.5x1.5 --right-of eDP1
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc monitor HDMI1 -d 6 7 8 9 10 
    bspc wm -O eDP1 HDMI1
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating

# default background
feh --bg-scale $HOME/.config/wallpapers/w1.jpg

source $HOME/.config/polybar/launch.sh

xset s 300 15
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

source $HOME/.config/bspwm/theme.sh

picom -b --backend glx

dunst

ibus-daemon -drxR 

xinput set-prop "MSHW0092:00 045E:0933 Touchpad" "libinput Tapping Enabled" 1
